server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mytests
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mappers/*.xml
pagehelper:
  dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true
